### PR TITLE
Add support for AWS SES

### LINKED ISSUE #36: Send email via SES
Hello,

I would like send email via that action using AWS SES API. Do you like support other transport? I would like provide PR for that.

This is about calling `sendEmail` in AWS SDK ( https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SES.html#sendEmail-property ) eg. via node-mailer transport ( https://nodemailer.com/transports/ses/ ).

Kind regards,

### PR DESCRIPTION
**Pull request by ad-m**
Close #36

### CODE REVIEW

**Comment by ad-m** [comment]
Is there anything how I can help you?

**Comment by dawidd6** [comment]
That's a lot of files. I actually didn't think it would be a diff that large. Tbh I'm not in favor of merging this in current state. Maybe you should consider making a separate Action for AWS SES?

**Comment by ad-m** [comment]
Thank you for your comment. It is not urgent for me to resolve this. If you don't mind - I will try to improve the AWS-SDK dependencies to solve it for everyone's benefit. I noticed that the "@aws-sdk/middleware-retry" package depends on the "react-native-get-random-values" package which depends on "react-native", which introduces 175 dependencies with a total weight of 254 MB:

```
/tmp/action-send-mail/node_modules/react-native$ npm ci
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated uglify-es@3.3.9: support for ECMAScript is superseded by `uglify-js` as of v3.13.0

added 714 packages, and audited 715 packages in 6s

17 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
/tmp/action-send-mail/node_modules/react-native$ du -s -h node_modules/ 
254M	node_modules/
```

**Comment by ad-m** [comment]
I have found that issue of `react-native` in `@aws-sdk/middleware-retry` is already reported in aws/aws-sdk-js-v3#2192 . There is overall process in aws to cleanup dependencies & reduce size aws/aws-sdk-js-v3#1536 especially on npm v7 which install peer dependencies by default. I updated that PR to skip `peerDependencies` via `npm install --legacy-peer-deps` to track progress.

**Comment by IgorM92** [comment]
you should not commit node_modules but install install them on run

**Comment by ad-m** [comment]
> you should not commit node_modules but install install them on run

Have you taken into account that this is GitHub Actions which does not install dependencies? See following [paragraph of GitHub documentation](https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action#commit-tag-and-push-your-action-to-github):

> This means you must include any package dependencies required to run the JavaScript code. You'll need to check in the toolkit core and github packages to your action's repository.
> From your terminal, commit your action.yml, index.js, node_modules, package.json, package-lock.json, and README.md files. If you added a .gitignore file that lists node_modules, you'll need to remove that line to commit the node_modules directory.

**Comment by ad-m** [comment]
I have bumpbed aws-ses client. Total size of node_modules is `26M` now (`6,3M` without AWS, so almost `20M` extra).

**Comment by dawidd6** [comment]
Sorry but I'm gonna pass. You can create a separate Action for sending mails using AWS. I think it is out of scope for this Action. Thanks anyway.

**Comment by SuchismitaGoswami** [comment]
@ad-m You can avoid pushing node_modules to the source code and build the project in the GitHub workflow to create the distribution. Then you can refer the dist/main.js in the action.yaml file.

**Pull request closed without merging**
