### PR TITLE
if email body is empty, then do not send out

### PR DESCRIPTION
**Pull request by donngchao**
if email body is empty, then do not send out

### CODE REVIEW

**Comment by dawidd6** [comment]
Why? People might want to send mails without body.

**Comment by donngchao** [comment]
Yes, you are right, but an empty email may not make much sense. Because I was bothered by empty emails before.

**Comment by dawidd6** [comment]
Sorry but I won't going to agree on this.

**Comment by donngchao** [comment]
Okay, maybe this feature is relatively niche.

**Pull request closed without merging**
