### PR TITLE
Resolve attachments via glob

### LINKED ISSUE #62: Allow globs for attachments
Hey! First of all thanks for this really nice action!

It'd be cool to be able to use globs for attachments:
```yml
- name: Send mail
  uses: dawidd6/action-send-mail@v3
  with:
    attachments: docs/*.pdf # Glob path!
```

This would attach all `.pdf` files in the `./docs` folder as single files.

I see that you're using JavaScript so [glob](https://www.npmjs.com/package/glob) might be something to use here?

### PR DESCRIPTION
**Pull request by Simonwep**
Resolves #62 

I didn't change anything else (you may want to set up [eslint](https://github.com/eslint/eslint) for consistency?). There are also no tests, I guess we'll just see how it works 😄

### CODE REVIEW

**Comment by dawidd6** [comment]
Why not https://github.com/actions/toolkit/tree/main/packages/glob

**Comment by Simonwep** [comment]
> Why not https://github.com/actions/toolkit/tree/main/packages/glob

Oh, that's even better! Yeah I haven't created an action so far, didn't know that there were special packages for it that I don't have to install, will do!

**Comment by Simonwep** [comment]
Whups, I was still missing some dependencies. Can you verify that it's now ok? :)

**Comment by fkrafi** [comment]
is it possible to merge and create a new release, I need to use it

**Comment by dawidd6** [comment]
Let's try this.

**Pull request merged**
